
name: 'Notify via slack'
description: 'Tell team team about a new build'
inputs:
  app_name: 
    description: Name of app being built
    required: false
  build_number: 
    description: Build number
    required: false
  build_type: 
    description: Build type
    required: false
  build_version: 
    description: Build version
    required: false
  config: 
    description: JSON object with config from previous run
  github_token:  # id of input
    description: 'The github actor token'
    required: true
  include_secrets:
    description: 'Return secrets with config'
    required: false
  notes: 
    description: 'additional notes'
    required: false
  ios_build_url: 
    description: 'The iOS build URL in EAS'
    required: false
  android_build_url: 
    description: 'The Android build URL in EAS'
    required: false
  slackbot_channel:
    description: slack channel for bot to post to
    required: true
  slackbot_secret: 
    description: slackbot app secret
    required: true
  slackbot_token:
    description: slackbot app token
    required: true
  status:  # id of input
    description: 'The status of the build'
    required: false
    default: 'working'
  title: 
    description: 'The title for the message'
    required: true
  ts: # id of slack thread
    description: 'The slack thread'

outputs:
  config: # output will be available to future steps
    description: 'The current slack thread'
runs:
  using: 'node20'
  main: 'dist/index.js'
  