
name: 'Notify via slack'
description: 'Tell team team about a new build'
inputs:
  build_number: 
    description: Build number
    required: false
  build_type: 
    description: Build type
    required: false
  build_version: 
    description: Build version
    required: false
  config: 
    description: JSON object with config from previous run
  github_token:  # id of input
    description: 'The github actor token'
    required: true
  include_secrets:
    description: 'Return secrets with config'
    required: false
  notes: 
    description: 'additional notes'
    required: false
  slackbot_channel:
    description: slack channel for bot to post to
  slackbot_secret: 
    description: slackbot app secret
  slackbot_token:
    description: slackbot app token
  status:  # id of input
    description: 'The status of the build'
    default: 'working'
  ts: # id of slack thread
    description: 'The slack thread'

outputs:
  config: # output will be available to future steps
    description: 'The current slack thread'
runs:
  using: 'node16'
  main: 'dist/index.js'
  